POST {{QuizGameAPI_HostAddress}}/api/users/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###

POST {{QuizGameAPI_HostAddress}}/api/users/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}
